framework:
    secret: not so secret but required to be set
sculpin_posts:
    permalink: blog/:year/:month/:day/:filename/
services:
 twig.extension.text:
     class: Twig_Extensions_Extension_Text
     tags:
         - { name: twig.extension }